### ISSUE TITLE
Cannot use attoseconds as units

### ISSUE THREAD

**Issue by cfe316** [OpenMDAO/OpenMDAO#1925]
### Summary of Issue

Attoseconds `as` cannot be used in the unit field. Femto and zeptoseconds work. Attometers `am` work.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

When I try to create a component which has an input or output with units of attoseconds (`as`), I get an error. The same does not occur for `am`, `fs`, or `zs`.

### Example
```
import openmdao.api as om

from scipy.constants import femto, atto, zepto

# this works fine
class FemtoConversion(om.ExplicitComponent):
    def setup(self):
        self.add_input("rate", units="1/s")
        self.add_output("rate_fs", units="fs**-1")

    def compute(self, inputs, outputs):
        rate = inputs["rate"]
        outputs["rate_fs"] = rate * femto

# this is broken
class AttoConversionBroken(om.ExplicitComponent):
    # as output
    def setup(self):
        self.add_input("rate", units="1/s")
        self.add_output("rate_as", units="as**-1")

    def compute(self, inputs, outputs):
        rate = inputs["rate"]
        outputs["rate_as"] = rate * atto

# this is broken
class AttoConversionBroken2(om.ExplicitComponent):
    # as input
    def setup(self):
        self.add_input("rate_as", units="1/as")
        self.add_output("rate", units="s**-1")

    def compute(self, inputs, outputs):
        rate = inputs["rate_as"]
        outputs["rate"] = rate / atto

# this works fine
class AttoConversionWorks(om.ExplicitComponent):
    # doesn't make /physical/ sense, but that's fine.
    def setup(self):
        self.add_input("rate", units="1/s")
        self.add_output("rate_am", units="am**-1")

    def compute(self, inputs, outputs):
        rate = inputs["rate"]
        outputs["rate_am"] = rate * atto

# this works fine
class ZeptoConversion(om.ExplicitComponent):
    def setup(self):
        self.add_input("rate", units="1/s")
        self.add_output("rate_zs", units="zs**-1")

    def compute(self, inputs, outputs):
        rate = inputs["rate"]
        outputs["rate_zs"] = rate * zepto

if __name__ == "__main__":
    prob = om.Problem()

    # succeeds
    # prob.model = FemtoConversion()

    # attoseconds as output: fails
    # prob.model = AttoConversionBroken()

    # attoseconds as input: fails
    prob.model = AttoConversionBroken2()

    # attometers: works
    # prob.model = AttoConversionWorks()

    # succeeds
    # prob.model = ZeptoConversion()

    prob.setup()

    prob.set_val("rate", 1.0e20, units="1/s")

    prob.run_driver()
```

This produces errors:
```
Traceback (most recent call last):
  File "/home/cfe316/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/utils/units.py", line 874, in _find_unit
    unit = _UNIT_CACHE[name]
KeyError: 'as**-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cfe316/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/utils/units.py", line 877, in _find_unit
    unit = eval(name, {'__builtins__': None}, _UNIT_LIB.unit_table)
  File "<string>", line 1
    as**-1
    ^
SyntaxError: invalid syntax
```
and some further errors as well.

I also cannot use `set_val` to set a quantity with `as`. It looks like it is being confused with the python keyword:

```
Traceback (most recent call last):
  File "/home/jacob/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/core/system.py", line 4770, in convert_from_units
    scale, offset = unit_conversion(units, base_units)
  File "/home/jacob/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/utils/units.py", line 1010, in unit_conversion
    return _find_unit(old_units, error=True).conversion_tuple_to(_find_unit(new_units, error=True))
  File "/home/jacob/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/utils/units.py", line 913, in _find_unit
    unit = eval(name, {'__builtins__': None}, _UNIT_LIB.unit_table)
  File "<string>", line 1
    1/as
      ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 74, in <module>
    prob.set_val("rate", 1.0e20, units="1/as")
  File "/home/jacob/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/core/problem.py", line 494, in set_val
    value = model.convert_from_units(abs_name, value, units)
  File "/home/jacob/.pyenv/versions/3.8.5/lib/python3.8/site-packages/openmdao/core/system.py", line 4773, in convert_from_units
    raise TypeError(msg.format(self.msginfo, name, base_units, units))
TypeError: <model> <class FemtoConversion>: Can't express variable 'rate' with units of '1/s' in units of '1/as'.

shell returned 1

Press ENTER or type command to continue
```

### Environment

OpenMDAO 3.7.0
Python 3.8.5

**Comment by JustinSGray** [comment]
this is going to be a little tricky to solve. `as` is a reserved word in python and the manner in which the unit lib works involves an eval call. so `as` is tricky. 

Making this work might involve a bit of a refactor in the unit library.

**Comment by cfe316** [comment]
I figured as such. I can certainly work around this by expressing things using `fs` or `zs` and using `ref` in outputs where applicable.

**Comment by robfalck** [comment]
The shortest path to fix this might just be to provide attoseconds with its own unique string.  `attoseconds` is a bit long, but is there any other non-SI standard name that might be acceptable?  `attosec` perhaps?

**Comment by cfe316** [comment]
I think either would be acceptable. I don't think `attosec` is ambiguous with anything else.

**Comment by JustinSGray** [comment]
its possible to define your own custom units in your runscript. I don't like adding `attosecond` to our default unit lib because it doesn't follow the rest. Id rather fix it properly. 

In the meantime as a workaround, you could define `attosecond` in your own runscripts. 

Here is the `add_unit` method.
https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/utils/units.py#L648

you can just import it and add the unit on the fly: 
```
from openmdao.utils.units import add_unit 
add_unit('attosec', '1e-18*s') 
```

That should keep you moving till we sort out a more permanent fix.

**Comment by cfe316** [comment]
Sounds good. Thank you for the suggestion! That should work just fine.

**Comment by JustinSGray** [comment]
**Note for developer who takes this on.** 

Unit.py currently uses eval which is a little dangerous. We could probably adapt the more safe method of expression parsing from the exec-comp instead.
