### ISSUE TITLE
Unable to run DOE in parallel due to Sqlite issue

### ISSUE THREAD

**Issue by makeclean** [OpenMDAO/OpenMDAO#2186]
### Summary of Issue

On Fedora 34, cant seem to run DOE in parallel and use the SQL Recorder

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

When running DOE in parallel with the SQLite3 recorder, the serial version works fine, but the parallel version results in the following error

```
04:55 $ mpirun -np 4 python3 doe_simple_parallel.py
Traceback (most recent call last):
  File "/home/adavis/prod/openmdao/example/doe_simple_parallel.py", line 26, in <module>
    prob.run_driver()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 661, in run_driver
Traceback (most recent call last):
  File "/home/adavis/prod/openmdao/example/doe_simple_parallel.py", line 26, in <module>
    prob.run_driver()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 661, in run_driver
Traceback (most recent call last):
  File "/home/adavis/prod/openmdao/example/doe_simple_parallel.py", line 26, in <module>
    prob.run_driver()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 661, in run_driver
    self.final_setup()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 983, in final_setup
    self.final_setup()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 983, in final_setup
    self.final_setup()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 983, in final_setup
    driver._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/drivers/doe_driver.py", line 280, in _setup_recording
    driver._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/drivers/doe_driver.py", line 280, in _setup_recording
    driver._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/drivers/doe_driver.py", line 280, in _setup_recording
    super()._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/driver.py", line 493, in _setup_recording
    super()._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/driver.py", line 493, in _setup_recording
    super()._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/driver.py", line 493, in _setup_recording
    self._rec_mgr.startup(self)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/recording_manager.py", line 107, in startup
    self._rec_mgr.startup(self)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/recording_manager.py", line 107, in startup
    self._rec_mgr.startup(self)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/recording_manager.py", line 107, in startup
    recorder.startup(recording_requester)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 309, in startup
    recorder.startup(recording_requester)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 309, in startup
    recorder.startup(recording_requester)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 309, in startup
    self._initialize_database()
    self._initialize_database()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 226, in _initialize_database
    self._initialize_database()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 223, in _initialize_database
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 223, in _initialize_database
    c.execute("CREATE TABLE global_iterations(id INTEGER PRIMARY KEY, "
sqlite3.OperationalError: table global_iterations already exists
    c.execute("CREATE TABLE driver_iterations(id INTEGER PRIMARY KEY, "
    c.execute("CREATE TABLE global_iterations(id INTEGER PRIMARY KEY, "
sqlite3.OperationalError: attempt to write a readonly database
sqlite3.OperationalError: disk I/O error
Traceback (most recent call last):
  File "/home/adavis/prod/openmdao/example/doe_simple_parallel.py", line 26, in <module>
    prob.run_driver()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 661, in run_driver
    self.final_setup()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/problem.py", line 983, in final_setup
    driver._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/drivers/doe_driver.py", line 280, in _setup_recording
    super()._setup_recording()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/core/driver.py", line 493, in _setup_recording
    self._rec_mgr.startup(self)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/recording_manager.py", line 107, in startup
    recorder.startup(recording_requester)
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 309, in startup
    self._initialize_database()
  File "/home/adavis/.local/lib/python3.9/site-packages/openmdao/recorders/sqlite_recorder.py", line 226, in _initialize_database
    c.execute("CREATE TABLE driver_iterations(id INTEGER PRIMARY KEY, "
sqlite3.OperationalError: disk I/O error
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[20221,1],3]
  Exit code:    1
--------------------------------------------------------------------------

```

### Example
The following works fine in serial
```
import openmdao.api as om
from openmdao.test_suite.components.paraboloid import Paraboloid

prob = om.Problem()
model = prob.model

model.add_subsystem('comp', Paraboloid(), promotes=['*'])

model.add_design_var('x', lower=-10, upper=10)
model.add_design_var('y', lower=-10, upper=10)
model.add_objective('f_xy')

prob.driver = om.DOEDriver(om.UniformGenerator(num_samples=5))
prob.driver.add_recorder(om.SqliteRecorder("cases.sql"))

prob.setup()

prob.set_val('x', 0.0)
prob.set_val('y', 0.0)

prob.run_driver()
prob.cleanup()

cr = om.CaseReader("cases.sql")
cases = cr.list_cases('driver')
```
However, below when run with mpirun -np 4 python3 example.py 
```
import openmdao.api as om
from openmdao.test_suite.components.paraboloid import Paraboloid

prob = om.Problem()
model = prob.model

model.add_subsystem('comp', Paraboloid(), promotes=['*'])

model.add_design_var('x', lower=-10, upper=10)
model.add_design_var('y', lower=-10, upper=10)
model.add_objective('f_xy')

prob.driver = om.DOEDriver(om.UniformGenerator(num_samples=5))
prob.driver.options['run_parallel'] = True
prob.driver.options['procs_per_model'] = 1
prob.driver.add_recorder(om.SqliteRecorder("cases.sql"))

prob.setup()

prob.set_val('x', 0.0)
prob.set_val('y', 0.0)

prob.run_driver()
prob.cleanup()

cr = om.CaseReader("cases.sql")
cases = cr.list_cases('driver')
```
### Environment

Fedora Core 34, Python 3.9

absl-py==0.13.0
argcomplete==1.12.0
astunparse==1.6.3
attrs==20.3.0
autobahn==21.2.2
Automat==20.2.0
backcall==0.2.0
Beaker==1.10.0
beautifulsoup4==4.9.3
blivet==3.3.3
blivet-gui==2.2.1
Brlapi==0.8.2
cachetools==4.2.2
cadquery==2.1
cffi==1.14.5
cftime==1.4.1
chardet==4.0.0
chrome-gnome-shell==0.0.0
clang==11.0
click==8.0.1
constantly==15.1.0
contextlib2==21.6.0
cryptography==3.4.6
csg2csg==0.0.27
cupshelpers==1.0
cycler==0.10.0
cymbal==1.0.0
Cython==0.29.21
dasbus==1.4
dbus-python==1.2.16
decorator==4.4.2
DeepXDE==0.11.2
distro==1.5.0
Equation==1.2.1
flatbuffers==1.12
fros==1.1
future==0.18.2
gast==0.4.0
gmsh==4.8.4
google-auth==1.32.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
gpg==1.15.1
grpcio==1.34.1
h5netcdf==0.11.0
h5py==3.1.0
humanize==0.5.1
hyperlink==21.0.0
idna==2.10
incremental==17.5.0
ipython==7.25.0
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
langtable==0.0.54
libcomps==0.1.17
logzero==1.7.0
lxml==4.6.3
Mako==1.1.4.dev0
Markdown==3.3.4
MarkupSafe==1.1.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mercurial==5.7.1
meshio==4.4.6
mpi4py==3.0.3
mpmath==1.2.1
netCDF4==1.5.5.1
networkx==2.5.1
nftables==0.1
numpy==1.21.0
oauthlib==3.1.1
olefile==0.46
openmc==0.13.0.dev0
openmc-plotter==0.1.0
openmdao==3.9.2
opt-einsum==3.3.0
packaging==20.9
pandas==1.3.0rc1
parso==0.8.2
Paste==3.5.0
path==16.0.0
pexpect==4.8.0
pickleshare==0.7.5
pid==2.2.3
Pillow==8.1.2
Pivy==0.6.5
ply==3.11
productmd==1.33
progressbar2==3.52.1
prompt-toolkit==3.0.19
protobuf==3.17.3
ptyprocess==0.6.0
pwquality==1.4.4
pyaml==20.4.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.6.2
pycairo==1.20.0
pycollada==0.7.1
pycparser==2.20
pycrypto==2.6.1
pycups==2.0.1
pycurl==7.43.0.6
pydicom==2.1.2
pyDOE2==1.3.0
pyenchant==3.2.0
pyexodus==0.1.3
Pygments==2.9.0
PyGObject==3.40.1
pykickstart==3.32
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyparted==3.11.7
PySide2==5.15.2
PySocks==1.7.1
python-augeas==0.5.0
python-dateutil==2.8.1
python-meh==0.50
python-utils==2.4.0
pytz==2021.1
pyudev==0.22.0
pywrap==0.1.dev0
pyxdg==0.27
PyYAML==5.4.1
requests==2.25.1
requests-file==1.5.1
requests-ftp==0.3.1
requests-oauthlib==1.3.0
rpm==4.16.1.3
rsa==4.7.2
schema==0.7.4
scikit-learn==0.24.2
scikit-optimize==0.8.1
scipy==1.7.0
selinux==3.2
sepolicy==3.2
service-identity==21.1.0
setools==4.4.0
shiboken2==5.15.2
simpleline==1.8
six==1.15.0
slip==0.6.4
slip.dbus==0.6.4
sos==4.1
soupsieve==2.2
sympy==1.8
systemd-python==234
Tempita==0.5.1
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
termcolor==1.1.0
threadpoolctl==2.1.0
toml==0.10.2
toposort==1.6
tqdm==4.61.1
traitlets==5.0.5
Twisted==21.2.0
txaio==21.2.1
typing-extensions==3.7.4.3
uncertainties==3.1.5
urllib3==1.25.10
wcwidth==0.2.5
Werkzeug==2.0.1
wrapt==1.12.1
zope.event==4.2.0
zope.interface==5.2.0

**Comment by makeclean** [comment]
Can confirm that this runs inside a docker container fine, seems like some local permissions issue?

**Comment by makeclean** [comment]
Ah, quick fingers, I think in my case/system, mpi tasks, 1,2 and 3 had less work to do, and thus tried to read a non-existent metadata file before mpi task 0 had created it, putting in an MPI.COMM_WORLD.Barrier() fixed that.

**Comment by swryan** [comment]
We haven't been able to replicate this but if you could submit a pull request with your fix, we would be happy to take a look at incorporating it.  Thanks!

**Comment by robfalck** [comment]
Closing since this should be implemented in the user's code.
