### ISSUE TITLE
"testflo openmdao -n 1" failure

### ISSUE THREAD

**Issue by thomasebrooks** [OpenMDAO/OpenMDAO#2196]
I ran the test code, and below is what it returned
------------------------------------------------
The following tests failed:
test_gui.py:

Passed:  2565
Failed:  1
Skipped: 472

Ran 3038 tests using 1 processes
Wall clock time:   00:06:28.86
------------------------------------------------

Here is my system spec

------------------------------------------------
import platform, sys

info = platform.uname()
(info.system, info.version), (info.machine, info.processor), sys.version
Out[1]: 
(('Windows', '10.0.18362'),
 ('AMD64', 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel'),
 '3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]')
------------------------------------------------

**Comment by naylor-b** [comment]
When you ran testflo you should have seen an error message associated with the failing test.  If you post that we may be able to diagnose the problem.   You only posted the summary, which tells which test(s) failed but gives no other information.  To find the error message you may be able to scroll back on your terminal until you see it, or you could check inside the `testflo_report.out` file that should have been written to your working directory when you ran testflo.

**Comment by thomasebrooks** [comment]
I believe this is it:

Traceback (most recent call last):
  File "c:\users\username\anaconda3\lib\site-packages\testflo\discover.py", line 136, in _module_iter
    fname, mod = get_module(filename)
  File "c:\users\username\anaconda3\lib\site-packages\testflo\util.py", line 376, in get_module
    mod = try_import(fname, modpath)
  File "c:\users\username\anaconda3\lib\site-packages\testflo\util.py", line 317, in try_import
    mod = import_module(modpath)
  File "c:\users\username\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\username\anaconda3\lib\site-packages\openmdao\visualization\n2_viewer\tests\test_gui.py", line 57, in <module>
    select_chromium_revision(current_platform())
  File "c:\users\username\anaconda3\lib\site-packages\openmdao\visualization\n2_viewer\tests\test_gui.py", line 30, in select_chromium_revision
    webf = urllib.request.urlopen(url)
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\username\anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by naylor-b** [comment]
It looks like your computer couldn't access the URL needed to determine the current chromium version.  You could try running the test again to see if this was just a temporary issue.  Otherwise there is some problem with your internet connection.  If this is the only failure you're getting, I wouldn't worry about it too much, because chromium is only used for the testing of our 'n2' diagram and is not used when running openmdao outside of testflo.

**Comment by thomasebrooks** [comment]
Okay, thanks!
