### ISSUE TITLE
Need better error message for when Problem.list_problem_vars is called before final_setup

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#2275]
### Summary of Issue

If `Problem.list_problem_vars` is called before `final_setup` is called, the user gets an error message which is not very helpful. 

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Should provide an error message telling user that `final_setup` needs to be called first, either explicitly, or by running `run_driver`. 

Can make use of the `setup_status` value in Problem

```
        if self._metadata['setup_status'] >= _SetupStatus.POST_FINAL_SETUP:
```

### Example
```   
    prob = om.Problem()
    prob.model.add_subsystem('parab', Paraboloid(), promotes_inputs=['x', 'y'])

    # define the component whose output will be constrained
    prob.model.add_subsystem('const', om.ExecComp('g = x + y'), promotes_inputs=['x', 'y'])

    # Design variables 'x' and 'y' span components, so we need to provide a common initial
    # value for them.
    prob.model.set_input_defaults('x', 3.0)
    prob.model.set_input_defaults('y', -4.0)

    # setup the optimization
    prob.driver = om.ScipyOptimizeDriver()
    prob.driver.options['optimizer'] = 'COBYLA'

    prob.model.add_design_var('x', lower=-50, upper=50)
    prob.model.add_design_var('y', lower=-50, upper=50)
    prob.model.add_objective('parab.f_xy')

    # to add the constraint to the model
    prob.model.add_constraint('const.g', lower=0, upper=10.)

    prob.setup()
    prob.list_problem_vars()
```

### Environment

NA

**Comment by naylor-b** [comment]
Also look at `list_inputs` and `list_outputs` when called before final_setup.  We got a report of this error message when `list_inputs` was called too early:
```
Traceback (most recent call last):
  File "conventional_problem.py", line 1455, in <module>
    scaling=args.scaling,
  File "/mnt/c/Users/jbergeso/TTT/GASP/ctol_weights/GASPy/util.py", line 21, in wrapper
    out = func(*args, **kwargs)
  File "conventional_problem.py", line 363, in conventional_problem
    prob = wt_defaults(prob)
  File "/mnt/c/Users/jbergeso/TTT/GASP/ctol_weights/GASPy/problem/set_wt_defaults.py", line 2, in wt_defaults
    print(prob.model.list_inputs(prom_name=True))
  File "/mnt/c/OMDAO/OpenMDAO/openmdao/core/system.py", line 3633, in list_inputs
    if self._problem_meta['setup_status'] < _SetupStatus.POST_FINAL_SETUP:
TypeError: 'NoneType' object is not subscriptable
```
