### ISSUE TITLE
ProbRemote4TestCase tests fail intermittently

### ISSUE THREAD

**Issue by tadkollar** [OpenMDAO/OpenMDAO#2283]
### Summary of Issue

Tests in this class can time out. They're currently disabled for GitHub Actions to prevent random failures, but they will sometimes fail to complete when running locally as well.

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Example

```
(mpi) /usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmdao/core/tests/test_prob_remote.py:ProbRemote4TestCase.test_prob_split_comm ... FAIL (00:00:0.00, 0 MB)
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/testflo/test.py", line 150, in _run_sub
    p = subprocess.run(cmd, stdout=stdout, stderr=stderr, env=env,
  File "/usr/share/miniconda/envs/test/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/share/miniconda/envs/test/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/share/miniconda/envs/test/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/share/miniconda/envs/test/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['mpirun', '-n', '4', '/usr/share/miniconda/envs/test/bin/python', '/usr/share/miniconda/envs/test/lib/python3.8/site-packages/testflo/mpirun.py', '/usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmdao/core/tests/test_prob_remote.py:ProbRemote4TestCase.test_prob_split_comm', '--coverage', '--coverpkg', 'openmdao']' timed out after 120.0 seconds
```

### Environment

Operating System: GitHub Actions Linux platforms

**Comment by robfalck** [comment]
Is this still an issue?  Can someone check on it and close if not?

**Comment by swryan** [comment]
Still an issue: https://github.com/swryan/OpenMDAO/actions/runs/3267459371/jobs/5372658602
