### ISSUE TITLE
Bug in case recorder or case reader

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2312]
### Summary of Issue

User reports the following error: 

```
LASLA18061774:~/projects/mphys/om_dash/example$ om_recorder_to_tec.py cases_LFD_flutter.sql 
Traceback (most recent call last):
  File "/usr/local/bin/om_recorder_to_tec.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/kejacob1/projects/mphys/om_dash/om_dash/om_recorder_to_tec.py", line 12, in <module>
    parser = RecorderParser(recorder_filename)
  File "/Users/kejacob1/projects/mphys/om_dash/om_dash/recorder_parser.py", line 10, in __init__
    self.read_histories_from_recorder(recorder_filename)
  File "/Users/kejacob1/projects/mphys/om_dash/om_dash/recorder_parser.py", line 17, in read_histories_from_recorder
    case_recorder = om.CaseReader(recorder_filename)
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/case_reader.py", line 26, in CaseReader
    return SqliteCaseReader(filename, pre_load, metadata_filename)
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/sqlite_reader.py", line 170, in __init__
    self._load_cases()
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/sqlite_reader.py", line 362, in _load_cases
    self._driver_cases._load_cases()
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/sqlite_reader.py", line 1257, in _load_cases
    for case in self.cases(cache=True):
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/sqlite_reader.py", line 1414, in cases
    case = Case('driver', row, self._prom2abs, self._abs2prom, self._abs2meta,
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/recorders/case.py", line 145, in __init__
    inputs = deserialize(data['inputs'], abs2meta, prom2abs, conns)
  File "/Users/kejacob1/projects/mphys/OpenMDAO/openmdao/utils/record_util.py", line 191, in deserialize
    values = json.loads(json_data)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1312519 (char 1312518)
```
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Case Reader works fine for a while, but after some number of iterations it gets broken somehow. Unclear if the error is in the data being written or read back. 

bad case data file available, but is over 350 mb... so can't attach here.

**Comment by swryan** [comment]
This does not appear to be a bug in the logic, but rather a data corruption issue. A fragment  of the JSON-encoded outputs dictionary was appended to the JSON-encoded inputs dictionary, as stored in the recording.

It's possible that this was the result of a OS/memory or file system problem. User reports that, after occurring ~5 times,  it has not happened again recently with the same model.

Leaving the issue open for now until there confidence that it does not re-occur.
