### ISSUE TITLE
Check partials stopped working with sparse subjacobian when upgrading from 3.8.0 to >3.9.0

### ISSUE THREAD

**Issue by bbahiam** [OpenMDAO/OpenMDAO#2354]
### Summary of Issue

Check partials stopped working with sparse subjacobian when upgrading from 3.8.0 to >3.9.0

### Issue Type

- [x] Bug
- [ ] Enhancement

### Description

There is an assignment problem when using FD to compute derivatives with a component that has a sparse Jacobian. I speculate it is due to a missing conversion from a diagonal sparse format to the COO sparse format, but I tried adding .tocoo() to all sparse matrices I created and it did not help.

### Example

This  [standalone example](https://gist.github.com/bbahiam/606e66d367ed0433f65a2689a4229f02) runs on OpenMDAO 3.8.0 but not on 3.9.0 (or 3.14.0). In that case it fails with the following output:
```
$ python test_cross_section_properties.py 
./home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/jacobians/jacobian.py:315: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  ncols = np.sum(end - start for _, start, end, _, _ in col_var_info.values())
EE
======================================================================
ERROR: test_partials_against_cs (__main__.TestCrossSectionProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cross_section_properties.py", line 249, in test_partials_against_cs
    assert_partials_match_fd(
  File "test_cross_section_properties.py", line 187, in assert_partials_match_fd
    data = prob.check_partials(method=method, out_stream=None)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/core/problem.py", line 1386, in check_partials
    approximation.compute_approximations(comp, jac=approx_jac)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/approximation_schemes/approximation_scheme.py", line 512, in compute_approximations
    jac.set_col(system, ic, col)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/jacobians/dictionary_jacobian.py", line 265, in set_col
    subjac['value'][:, loc_idx] = column[start:end]
TypeError: 'dia_matrix' object does not support item assignment

======================================================================
ERROR: test_partials_against_fd (__main__.TestCrossSectionProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cross_section_properties.py", line 244, in test_partials_against_fd
    assert_partials_match_fd(
  File "test_cross_section_properties.py", line 187, in assert_partials_match_fd
    data = prob.check_partials(method=method, out_stream=None)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/core/problem.py", line 1386, in check_partials
    approximation.compute_approximations(comp, jac=approx_jac)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/approximation_schemes/approximation_scheme.py", line 512, in compute_approximations
    jac.set_col(system, ic, col)
  File "/home/bbahia/tmp/venv/lib/python3.8/site-packages/openmdao/jacobians/dictionary_jacobian.py", line 265, in set_col
    subjac['value'][:, loc_idx] = column[start:end]
TypeError: 'dia_matrix' object does not support item assignment

----------------------------------------------------------------------
Ran 3 tests in 0.023s

FAILED (errors=2)
```

### Environment

Operating System: Ubuntu 20.04.3 LTS Linux 5.4.0-89-generic

Python environment: Python 3.8.10

Packages: 
```
$ pip freeze
certifi==2021.10.8
charset-normalizer==2.0.7
idna==3.3
networkx==2.6.3
numpy==1.21.4
openmdao==3.9.0
pyDOE2==1.3.0
pyparsing==3.0.6
requests==2.26.0
scipy==1.7.2
urllib3==1.26.7
```

**Comment by Kenneth-T-Moore** [comment]
Thanks for reporting the bug. I've got a fix up on a Pull Request right now, but i wanted to make sure that you know that you can also let OpenMDAO handle the sparsity of these jacobians by declaring partials with `rows` and `columns`.  With this, you only have to provide the diagonal elements as an ndarray of length n for each sub-jacobian.

An advantage of doing it this way is that OpenMDAO knows the sparsity pattern, so that you can use the total derivative coloring feature for faster performance.

[I've modified your standalone example to show how to do it:](https://gist.github.com/Kenneth-T-Moore/45c7b67728b902d7decd344265986c4c).
