### ISSUE TITLE
Surrogate `test_comp_map` fails on Windows

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/OpenMDAO#2471]
### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

`test_comp_map` in `openmdao\surrogate_models\tests\test_map.py` fails  on Windows:

```
Traceback (most recent call last):
  File "C:\Users\swryan\Anaconda3\envs\om316\lib\site-packages\testflo\test.py", line 418, in _try_call
    func()
  File "C:\Users\swryan\Anaconda3\envs\om316\lib\site-packages\openmdao\surrogate_models\tests\test_map.py", line 65, in test_comp_map
    assert_near_equal(p['compmap.eff'], p['compmap.Nc']*p['compmap.Rline']**2+p['compmap.alpha'], tol)
  File "C:\Users\swryan\Anaconda3\envs\om316\lib\site-packages\openmdao\utils\assert_utils.py", line 521, in assert_near_equal
    raise ValueError('actual %s, desired %s, rel error %s, tolerance %s'
ValueError: actual [3.6], desired [4.1895], rel error 0.1407089151450053, tolerance 0.1
```

See: https://stackoverflow.com/questions/71473463/openmdao-testflo-1-failed-case-test-map-pytestmap-test-comp-map-and-612-ski

Note that the test passes with `python=3.8 numpy=1.18 scipy=1.4`

The GitHub workflow should be updated to use the latest versions of python, numpy and scipy on Windows when this test is fixed.

### Example

See `test_comp_map`

### Environment

Operating System: Windows 10

Python environment: Anaconda Python 3.9

Packages: 
```
# packages in environment at C:\Users\swryan\Anaconda3\envs\om316:
#
# Name                    Version                   Build  Channel
aiounittest               1.4.1                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2022.2.1             haa95532_0
certifi                   2021.10.8        py39haa95532_2
charset-normalizer        2.0.12                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  4.5.4                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
greenlet                  1.1.2                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
jinja2                    3.0.3                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
networkx                  2.7.1                    pypi_0    pypi
numpy                     1.21.5           py39ha4e8547_0
numpy-base                1.21.5           py39hc2deb75_0
numpydoc                  1.2                      pypi_0    pypi
openmdao                  3.16.0                   pypi_0    pypi
openssl                   1.1.1m               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
parameterized             0.8.1                    pypi_0    pypi
pip                       21.2.4           py39haa95532_0
playwright                1.14.1                   pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pydocstyle                2.0.0                    pypi_0    pypi
pydoe2                    1.3.0                    pypi_0    pypi
pyee                      9.0.4                    pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
python                    3.9.7                h6244533_1
pytz                      2021.3                   pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
scipy                     1.7.3            py39h0a974cb_0
setuptools                58.0.4           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.38.0               h2bbff1b_0
testflo                   1.4.8                    pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
websockets                10.2                     pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
wrapt                     1.14.0                   pypi_0    pypi
zipp                      3.7.0                    pypi_0    pypi
```

**Comment by swryan** [comment]
Note: test does not fail with Numpy 1.21 and Scipy 1.62... seems to break with Scipy 1.7
