### ISSUE TITLE
Distributed inputs/outputs with empty arrays no longer work in 3.17

### ISSUE THREAD

**Issue by timryanb** [OpenMDAO/OpenMDAO#2498]
### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

I am no longer able to run OpenMDAO models with components that use distributed inputs/outputs where one of the arrays is empty on a processor. It seems like some change was made internally in OpenMDAO for how components with distributed arrays are handled between 3.16 and 3.17, because the error doesn't occur in prior versions.

### Example

```
"""
This example has a single ExplicitComponent that takes an input vector
from the root proc and broadcasts it as a serial output on all processors.
An IVC is added to the model feed this component inputs.

This case fails at setup in OpenMDAO 3.17, but works for prior versions.
It seems to have to do with the fact that one of the distributed arrays uses an empty vector on one of the processors
(the root one is non-empty). This case works in >3.17
"""

import numpy as np
import openmdao.api
import openmdao.api as om
from openmdao.utils.mpi import MPI

if MPI is None:
    print("This example must be run in parallel with at least 2 procs.")
    # exit()

# Input vector on root to be broadcast
in_vec = np.arange(3)
vec_len = len(in_vec)


class BCastComp(om.ExplicitComponent):
    """
    Broadcast a vector from the root to all other processors.
    The output of this component is a serial vector.
    """

    def setup(self):
        # Distributed input, only one proc will have non-empty vector
        self.add_input('in_dist', shape_by_conn=True, distributed=True)

        # Serial Output (every processor has the same output vector)
        self.add_output('out_serial', shape=vec_len)

    def compute(self, inputs, outputs):
        # Root processor broadcasts values to everyone else
        outputs['out_serial'] = self.comm.bcast(inputs['in_dist'], root=0)

    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        if mode == 'fwd':
            if 'out_serial' in d_outputs:
                if 'in_dist' in d_inputs:
                    d_outputs['out_serial'] += self.comm.bcast(d_inputs['in_dist'], root=0)

        else:  # 'rev'
            if 'out_serial' in d_outputs:
                if 'in_dist' in d_inputs:
                    if self.comm.rank == 0:
                        d_inputs['in_dist'] += d_outputs['out_serial']


class Model(openmdao.api.Group):
    """
    Simple group to hold problem components
    """

    def setup(self):
        # Create a distributed source for the distributed input.
        ivc = om.IndepVarComp()
        # Root processor gets input vector
        if self.comm.rank == 0:
            ivc.add_output('x_dist', val=in_vec, shape=vec_len, distributed=True)
        # Every other proc has empty input
        else:
            ivc.add_output('x_dist', shape=0, distributed=True)

        self.add_subsystem("indep", ivc)
        self.add_subsystem("bcast", BCastComp())

        self.connect('indep.x_dist', 'bcast.in_dist')

        self.add_design_var('indep.x_dist')
        self.add_constraint('bcast.out_serial', lower=0.0)


# Create problem
prob = om.Problem()

# Set model
prob.model = Model()

prob.setup(force_alloc_complex=True, mode='rev')

prob.run_model()

```

The above example returns the following error message when run with 2 processors:
```
Traceback (most recent call last):
  File "/Users/trbrooks/Downloads/dist.py", line 85, in <module>
    prob.setup(force_alloc_complex=True, mode='rev')
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/core/problem.py", line 1014, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/core/system.py", line 864, in _setup
    self._top_level_post_sizes()
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/core/group.py", line 809, in _top_level_post_sizes
    comp._update_dist_src_indices(conns, all_abs2meta, abs2idx,
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/core/component.py", line 959, in _update_dist_src_indices
    meta_in['src_indices'] = indexer(slice(offset, end), flat_src=True,
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/utils/indexer.py", line 1333, in __call__
    idxer.set_src_shape(src_shape)
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/utils/indexer.py", line 269, in set_src_shape
    self._check_bounds()
  File "/Users/trbrooks/miniconda3/envs/OpenMDAO/lib/python3.9/site-packages/openmdao/utils/indexer.py", line 606, in _check_bounds
    raise IndexError(f"{self._slice} is out of bounds of the source shape "
IndexError: slice(3, 3, None) is out of bounds of the source shape (3,).
```

### Environment

OS X & Ubuntu

Python environment: Anaconda Python 3.8 & 3.9

Packages: OpenMDAO==3.17

**Comment by joanibal** [comment]
We believe we are encountering the same issue with our adflow examples in [MPhys](https://github.com/OpenMDAO/mphys/pull/100).

**Comment by joanibal** [comment]
Possibly related to [This PR](https://github.com/OpenMDAO/OpenMDAO/pull/2495) and [this issue](https://github.com/OpenMDAO/OpenMDAO/issues/2494)
