### ISSUE TITLE
A coding error occurred when I used the (prob.run_driver) function

### ISSUE THREAD

**Issue by Gcstk** [OpenMDAO/OpenMDAO#2562]
### Issue Type

- [x] Bug

### Description
When I tried to run the examples of versions 3.17 and 3.19,  An error occurred in prob.run_driver()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 101887: illegal multibyte sequence
I'm sure this is a mistake in the framework.

### Example

``` python
import openmdao.api as om
from openmdao.test_suite.components.sellar_feature import SellarMDA

prob = om.Problem()
prob.model = SellarMDA()

prob.driver = om.ScipyOptimizeDriver()
prob.driver.options['optimizer'] = 'SLSQP'
prob.driver.options['tol'] = 1e-8

prob.model.add_design_var('x', lower=0, upper=10)
prob.model.add_design_var('z', lower=0, upper=10)
prob.model.add_objective('obj')
prob.model.add_constraint('con1', upper=0)
prob.model.add_constraint('con2', upper=0)
prob.model.approx_totals()

prob.setup()
prob.set_solver_print(level=0)

prob.run_driver()
```
Details of error reporting:
       Traceback (most recent call last):
  File "B:/Literature_reference/opt/MDO/OpenMDAO/pythonCode/openMDAO/com/geotk/test/Test.py", line 29, in <module>
    prob.run_driver()
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\core\problem.py", line 753, in run_driver
    return self.driver.run()
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 532, in run
    self._reraise()
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 778, in _reraise
    raise self._exc_info[1].with_traceback(self._exc_info[2])
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\drivers\scipy_optimizer.py", line 700, in _gradfunc
    grad = self._compute_totals(of=self._obj_and_nlcons, wrt=self._dvlist,
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\utils\hooks.py", line 119, in execute_hooks
    _run_hooks(post_hooks, inst)
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\utils\hooks.py", line 92, in _run_hooks
    hook(inst, **kwargs)
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\utils\reports_system.py", line 307, in run_scaling_report_inner
    prob.driver.scaling_report(outfile=scaling_filepath, show_browser=False)
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\core\driver.py", line 1131, in scaling_report
    return view_driver_scaling(self, outfile=outfile, show_browser=show_browser, jac=jac,
  File "D:\program_02\Anaconda\envs\openmdao\lib\site-packages\openmdao\visualization\scaling_viewer\scaling_report.py", line 456, in view_driver_scaling
    d3_src = f.read()
**UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 101887: illegal multibyte sequence**

### Environment

<For bugs>

Operating System: <Windows 10>

Python environment: <i.e. Anaconda Python 3.8>

Packages: <openmdao   3.17.0   pyhd8ed1ab_0 & openmdao   3.19.0   pyhd8ed1ab_0>

**Comment by Gcstk** [comment]
This problem did not occur after I downgraded the version to 3.10

**Comment by robfalck** [comment]
This sort of error is usually the result of copy-paste errors.  Some text editors will allow you to remove non-ascii characters.  Saving this file with the offending characters removed should resolve the problem.

**Comment by naylor-b** [comment]
This looks like some sort of issue with a javascript library we use for our scaling report viewer.  As a temporary workaround, you can turn off the default reports (which includes the scaling report viewer) by setting `OPENMDAO_REPORTS=0` in your environment.
