### ISSUE TITLE
setuptools v65.0.0 breaks pyoptsparse install

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/OpenMDAO#2611]
### Task Description

[setuptools v65.0.0](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#breaking-changes) breaks the `pyoptsparse` install with the following error:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/tmp/tmpbqewnkqh/setup.py", line 8, in <module>
          import numpy.distutils.core
        File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

see: https://github.com/pypa/setuptools/pull/3505

We will need to pin `setuptools<v65.0.0` in the workflow for now.

**Comment by swryan** [comment]
This issue has been addressed by https://github.com/OpenMDAO/build_pyoptsparse/pull/33

**Comment by nwu63** [comment]
How can the pyOS team make things easier for you guys? Should we also pin setuptools<65 in the yaml file? Also feel free to ping us anytime if you would like to see some change in the code, pyOS has a much larger user base through OM and you guys end up having to deal with a lot of installation issues that don't really have anything to do with OM itself.
