### ISSUE TITLE
failed testflo openmdao -n 1

### ISSUE THREAD

**Issue by dickyaditama** [OpenMDAO/OpenMDAO#2645]
(info.system, info.version), (info.machine, info.processor), sys.version
(('Windows', '10.0.19044'), ('AMD64', 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel'), '3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]')

error message :
..........................................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........SUCCESS: The process with PID 7580 (child process of PID 18424) has been terminated.
SUCCESS: The process with PID 18424 (child process of PID 20444) has been terminated.
.......SS.......SSSSSSSSSSSSS....................................................................S.....................................................................................................................................................S..................S............S.......SSSSSSSSSSSSSSSSSS.................S..SS...................................................................................SSSSSSS..........SSS............SSSSSSSSSSSS..S.............................S.SSSSS....S....................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................................................SS........................SSSS..SSSSSSSSSSSSSSS..SSSSS.SSSSSSSSSSSSSSSSSSSSS.SSSSSSSSSSSSSSSSSSSSSSS....................SSS.SSSSSSSS...............S......SS....................S.....SS........SS...SS.........SS........S...........................................................................................................................................SSSS.........................SSSSSSSSSSSSSSSSS.S...........................................................................SSS....................SSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SSSSSSSSSS.....SSSSSSSSSSSSSSSSS.....SSS.SSSSSS....................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............................................SSSSSS............................................................................SSSSSSSSSSSSSSS.SSSSSSSSS.......S.....................
   Normal return from subroutine COBYLA

   NFVALS =   61   F =-2.733333E+01    MAXCV = 0.000000E+00
   X = 6.666667E+00  -7.333332E+00
....
   Normal return from subroutine COBYLA

   NFVALS =   61   F =-2.733333E+01    MAXCV = 0.000000E+00
   X = 6.666667E+00  -7.333332E+00
Downloading Webkit 16.0 (playwright build v1715) - 58.2 Mb [====================] 100% 0.0s
Webkit 16.0 (playwright build v1715) downloaded to C:\Users\dicky\AppData\Local\ms-playwright\webkit-1715
SSSSSSSSSSSSS........................................................SSSSSSSSSSSSSSSSSSSS..................................SSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............................................................S................................................................................................................................................SSSSSSS............................S.......................................................................................................................................S...S.....................................SSSSS..............................................................SSSSSSSSSSSSSSSS..........................SSSS.......................................................................................SS...................S...S...............S................................C:\Users\dicky\anaconda3\lib\site-packages\openmdao\surrogate_models\tests\test_map.py:TestMap.test_comp_map ... FAIL (00:00:0.02, 188 MB)
Traceback (most recent call last):
  File "C:\Users\dicky\anaconda3\lib\site-packages\testflo\test.py", line 418, in _try_call
    func()
  File "C:\Users\dicky\anaconda3\lib\site-packages\openmdao\surrogate_models\tests\test_map.py", line 65, in test_comp_map
    assert_near_equal(p['compmap.eff'], p['compmap.Nc']*p['compmap.Rline']**2+p['compmap.alpha'], tol)
  File "C:\Users\dicky\anaconda3\lib\site-packages\openmdao\utils\assert_utils.py", line 521, in assert_near_equal
    raise ValueError('actual %s, desired %s, rel error %s, tolerance %s'
ValueError: actual [3.6], desired [4.1895], rel error 0.1407089151450053, tolerance 0.1

.............................................
   Normal return from subroutine COBYLA

   NFVALS =   54   F =-2.700000E+01    MAXCV = 0.000000E+00
   X = 6.999999E+00  -6.999999E+00
......S........................................S...........................C:\Users\dicky\anaconda3\lib\site-packages\openmdao\utils\general_utils.py:87: SetupWarning:'sub' <class Group>: Attempted to connect from 'tgt.x' to 'cmp.x', but 'tgt.x' is an input. All connections must be from an output to an input.
..........................................................S....................................................................S............SC:\Users\dicky\anaconda3\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning:Setuptools is replacing distutils.
......................................................SSS..........................................................S.S.............S..S....SS..SSS...

The following tests failed:
test_map.py:TestMap.test_comp_map

Passed:  2844
Failed:  1
Skipped: 622

Ran 3467 tests using 1 processes
Wall clock time:   00:20:44.10

**Comment by swryan** [comment]
This is a known issue #2471 apparently with Scipy 1.7  on Windows, and is still on the agenda to be fixed.

If you need this feature, you might try a different version of SciPy as a workaround.
