### ISSUE TITLE
check_partials() fails for ExplicitComponent with both 'standard' and matrix-free derivatives

### ISSUE THREAD

**Issue by peterjrohrer** [OpenMDAO/OpenMDAO#3104]
### Description

For an ExplicitComponent class with partial derivatives defined using `compute_partials()` and `compute_jacvec_product()` the `check_partials()` function throws an fairly vague error about item assignment, included below.  `check_partials()` seems to work just fine for an ExplicitComponent with partial derivatives defined using either `compute_partials()` OR `compute_jacvec_product()`

My understanding is that an ExplicitComponent class can implement `compute_partials()` and/or `compute_jacvec_product()` or neither.

The full error message is:
```
Traceback (most recent call last):
  File "/.../lib/python3.11/site-packages/openmdao/core/system.py", line 2674, in _call_user_function
    yield
  File "/.../lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 496, in _compute_partials_wrapper
    self.compute_partials(self._inputs, self._jacobian)
  File "/.../test_matfree.py", line 17, in compute_partials
    partials['area', 'length'] = inputs['width']
    ~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../test_matfree.py", line 43, in <module>
    data = prob.check_partials(compact_print=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/openmdao/core/problem.py", line 1333, in check_partials
    comp.run_linearize(sub_do_ln=False)
  File "/.../lib/python3.11/site-packages/openmdao/core/system.py", line 4607, in run_linearize
    self._linearize(self._assembled_jac, sub_do_ln=do_ln)
  File "/.../lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 522, in _linearize
    self._compute_partials_wrapper()
  File "/.../lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 481, in _compute_partials_wrapper
    with self._call_user_function('compute_partials'):
  File "/.../lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/.../lib/python3.11/site-packages/openmdao/core/system.py", line 2680, in _call_user_function
    raise err_type(
  File "/.../lib/python3.11/site-packages/openmdao/core/system.py", line 2674, in _call_user_function
    yield
  File "/.../lib/python3.11/site-packages/openmdao/core/explicitcomponent.py", line 496, in _compute_partials_wrapper
    self.compute_partials(self._inputs, self._jacobian)
  File "/.../test_matfree.py", line 17, in compute_partials
    partials['area', 'length'] = inputs['width']
    ~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'comp' <class RectangleComp>: Error calling compute_partials(), 'NoneType' object does not support item assignment
```

### Example

```
import numpy as np
import openmdao.api as om

class RectangleComp(om.ExplicitComponent):
    def setup(self):
        self.add_input('length', val=1.)
        self.add_input('width', val=1.)
        self.add_output('area', val=1.)

    def setup_partials(self):
        self.declare_partials(of='*', wrt='*')

    def compute(self, inputs, outputs):
        outputs['area'] = inputs['length'] * inputs['width']

    def compute_partials(self, inputs, partials):
        partials['area', 'length'] = inputs['width']
        partials['area', 'width'] = inputs['length']

    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        if mode == 'fwd':
            if 'area' in d_outputs:
                if 'length' in d_inputs:
                    d_outputs['area'] += inputs['width'] * d_inputs['length']
                if 'width' in d_inputs:
                    d_outputs['area'] += inputs['length'] * d_inputs['width']
        elif mode == 'rev':
            if 'area' in d_outputs:
                if 'length' in d_inputs:
                    d_inputs['length'] += inputs['width'] * d_outputs['area']
                if 'width' in d_inputs:
                    d_inputs['width'] += inputs['length'] * d_outputs['area']

prob = om.Problem()

prob.model.add_subsystem('comp', RectangleComp())

prob.set_solver_print(level=0)

prob.setup(mode='rev')
prob.run_model()

data = prob.check_partials(compact_print=True)
```

### OpenMDAO Version

3.30.0

### Relevant environment information

Running on WSL Ubuntu 22, Python 3.11
Relevant environment information:
```
jax==0.4.21
jaxlib==0.4.21+cuda12.cudnn89
kiwisolver==1.4.5
matplotlib==3.8.2
ml-dtypes==0.3.1
networkx==3.2.1
numpy==1.26.2
nvidia-cublas-cu12==12.3.4.1
nvidia-cuda-cupti-cu12==12.3.101
nvidia-cuda-nvcc-cu12==12.3.103
nvidia-cuda-nvrtc-cu12==12.3.103
nvidia-cuda-runtime-cu12==12.3.101
nvidia-cudnn-cu12==8.9.6.50
nvidia-cufft-cu12==11.0.12.1
nvidia-cusolver-cu12==11.5.4.101
nvidia-cusparse-cu12==12.2.0.103
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
openmdao==3.30.0
opt-einsum==3.3.0
packaging==23.2
pandas==2.1.3
Pillow==10.1.0
pyDOE2==1.3.0
pyDOE3==1.0.1
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
requests==2.31.0
scipy==1.11.4
six==1.16.0
tzdata==2023.3
urllib3==2.1.0
xarray==2023.11.0
```

**Comment by robfalck** [comment]
This error message doesn't help much, but recently OpenMDAO was changed such that partials are to be provided with either matrix free OR the compute_partials interface, but not both

https://github.com/OpenMDAO/POEMs/blob/master/POEM_091.md

**Comment by peterjrohrer** [comment]
Thanks for the clarification!  I had missed that POEM, but the change makes a lot of sense.  I'll close the comment.

It looks like the last line of the [docs here](https://openmdao.org/newdocs/versions/latest/features/core_features/working_with_components/explicit_component.html#the-matrix-free-api-providing-derivatives-as-a-matrix-vector-product) hasn't been updated yet?

**Comment by naylor-b** [comment]
Good catch!  I put in an issue to fix that section of the docs.
