### ISSUE TITLE
Issue with pyoptsparse driver on GitHub workflows

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/OpenMDAO#3109]
### Task Description

A new issue with running tests on GitHub Actions...    it may be intermittent?

`pyoptsparse` installs successfully, but there is some issue with instantiating pyOptSparseDriver that only seems to happen when running a test under testflo..    Manually instantiating the driver interactively works fine.
 
```
runner@fv-az1567-34:~$ testflo -n 1 -x openmdao.utils.tests
............./usr/share/miniconda/envs/test/lib/python3.12/site-packages/openmdao/utils/tests/test_reports_system.py:TestReportsSystem.test_report_generation_basic_pyoptsparse  ... FAIL (00:00:0.00, 278 MB)
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.12/site-packages/openmdao/utils/tests/test_hooks.py", line 22, in _wrapper
    f(*args, **kwargs)
  File "/usr/share/miniconda/envs/test/lib/python3.12/site-packages/openmdao/utils/tests/test_reports_system.py", line 186, in test_report_generation_basic_pyoptsparse
    prob = self.setup_and_run_simple_problem(driver=pyOptSparseDriver(optimizer='SLSQP'))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/test/lib/python3.12/site-packages/openmdao/drivers/pyoptsparse_driver.py", line 193, in __init__
    raise RuntimeError('pyOptSparseDriver is not available, pyOptsparse is not installed.')
RuntimeError: pyOptSparseDriver is not available, pyOptsparse is not installed.



The following tests failed:
test_reports_system.py:TestReportsSystem.test_report_generation_basic_pyoptsparse


Passed:  13
Failed:  1
Skipped: 0


Ran 14 tests using 1 processes
Wall clock time:   00:00:2.16

runner@fv-az1567-34:~$ python
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmdao.api as om
>>> driver=om.pyOptSparseDriver(optimizer='SLSQP')
>>>
```

see: https://github.com/OpenMDAO/OpenMDAO/actions/runs/7744705884/job/21119055933

**Comment by swryan** [comment]
Running the test in isolation with `testflo` also works:
```
runner@fv-az1567-34:~$ testflo -n 1 -vs  openmdao.utils.tests.test_reports_system:TestReportsSystem.test_report_generation_basic_pyoptsparse


Optimization Problem -- Optimization using pyOpt_sparse
================================================================================
    Objective Function: _objfunc

    Solution:
--------------------------------------------------------------------------------
    Total Time:                    0.0073
       User Objective Time :       0.0003
       User Sensitivity Time :     0.0058
       Interface Time :            0.0008
       Opt Solver Time:            0.0004
    Calls to Objective Function :       2
    Calls to Sens Function :            2


   Objectives
      Index  Name            Value
          0  f_xy     1.700000E+01

   Variables (c - continuous, i - integer, d - discrete)
      Index  Name   Type      Lower Bound            Value      Upper Bound     Status
          0  x_0      c     0.000000E+00     1.000000E+00     1.000000E+00          u
          1  y_0      c     0.000000E+00     3.375078E-14     1.000000E+00          l


   Exit Status
      Inform  Description
           0  Optimization terminated successfully.
--------------------------------------------------------------------------------

openmdao.utils.tests.test_reports_system:TestReportsSystem.test_report_generation_basic_pyoptsparse ... OK (00:00:0.17, 273 MB)


OK

Passed:  1
Failed:  0
Skipped: 0


Ran 1 test using 1 processes
Wall clock time:   00:00:1.95

runner@fv-az1567-34:~$
```
