### ISSUE TITLE
Test failure with Scipy 1.13.0rc1

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/OpenMDAO#3156]
### Description

`test_newton_with_cscjac_under_cs` fails with [Scipy 1.13.0](https://github.com/scipy/scipy/releases/tag/v1.13.0rc1) _release candidate_.

### Example

```
(latest) swryan@Chimaera:~/dev/OpenMDAO/openmdao/core/tests$ testflo -vs test_approx_derivs.py:TestGroupComplexStep.test_newton_with_cscjac_under_cs
NL: NewtonSolver 'NL: Newton' on system 'sub' failed to converge in 10 iterations.
test_approx_derivs.py:TestGroupComplexStep.test_newton_with_cscjac_under_cs  ... FAIL (00:00:0.03, 268 MB)
Traceback (most recent call last):
  File "/home/swryan/dev/OpenMDAO/openmdao/core/tests/test_approx_derivs.py", line 1629, in test_newton_with_cscjac_under_cs
    assert_near_equal(J['obj', 'x'][0][0], 2.98061391, 1.0e-6)
  File "/home/swryan/dev/OpenMDAO/openmdao/utils/assert_utils.py", line 574, in assert_near_equal
    raise ValueError('actual %s, desired %s, rel error %s, tolerance %s'
ValueError: actual [2.84522616], desired [2.98061391], rel error 0.045422774462393824, tolerance 1e-06



The following tests failed:
test_approx_derivs.py:TestGroupComplexStep.test_newton_with_cscjac_under_cs


Passed:  0
Failed:  1
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:3.24

(latest) swryan@Chimaera:~/dev/OpenMDAO/openmdao/core/tests$ pip install "scipy<1.13"
Collecting scipy<1.13
  Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Requirement already satisfied: numpy<1.29.0,>=1.22.4 in /home/swryan/miniconda3/envs/latest/lib/python3.12/site-packages (from scipy<1.13) (1.26.4)
Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.8 MB)
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.0rc1
    Uninstalling scipy-1.13.0rc1:
      Successfully uninstalled scipy-1.13.0rc1
Successfully installed scipy-1.12.0
[09:57:28](latest) swryan@Chimaera:~/dev/OpenMDAO/openmdao/core/tests$ !te
testflo -vs test_approx_derivs.py:TestGroupComplexStep.test_newton_with_cscjac_under_cs
test_approx_derivs.py:TestGroupComplexStep.test_newton_with_cscjac_under_cs ... OK (00:00:0.03, 265 MB)


OK

Passed:  1
Failed:  0
Skipped: 0


Ran 1 test using 12 processes
Wall clock time:   00:00:3.28
```

### OpenMDAO Version

3.31.2-dev

**Comment by swryan** [comment]
SciPy 1.13.0 has been [released](https://github.com/scipy/scipy/releases/tag/v1.13.0)
