### ISSUE TITLE
Makefile:66: recipe for target 'buildall' failed

### ISSUE THREAD

**Issue by capsulecorplab** [OpenMDAO/OpenMDAO#758]
Encountered the following while running `make all` in openmdao/docs...
```
$ make all
touch make_sourcedocs
python _utils/preprocess_tags.py
sphinx-build -a -b html -d _build/doctrees  . _build/html
Running Sphinx v1.7.9
making output directory...
loading pickled environment... not yet created
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 328 added, 0 changed, 0 removed
reading sources... [ 42%] basic_guide/first_optimization                                                                 
   Normal return from subroutine COBYLA

   NFVALS =   54   F =-2.700000E+01    MAXCV = 0.000000E+00
   X = 6.999999E+00  -6.999999E+00
[saiyaman-Lenovo-U310:19019] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0) of (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0/37999/0/0), mkdir failed [1]
[saiyaman-Lenovo-U310:19019] [[37999,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[saiyaman-Lenovo-U310:19019] [[37999,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 402
[saiyaman-Lenovo-U310:19019] [[37999,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 638
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[saiyaman-Lenovo-U310:19021] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0) of (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0/37993/0/0), mkdir failed [1]
[saiyaman-Lenovo-U310:19021] [[37993,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[saiyaman-Lenovo-U310:19021] [[37993,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 402
[saiyaman-Lenovo-U310:19021] [[37993,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 638
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[saiyaman-Lenovo-U310:19023] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0) of (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0/37995/0/0), mkdir failed [1]
[saiyaman-Lenovo-U310:19023] [[37995,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[saiyaman-Lenovo-U310:19023] [[37995,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 402
[saiyaman-Lenovo-U310:19023] [[37995,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 638
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[saiyaman-Lenovo-U310:19025] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0) of (/tmp/openmpi-sessions-saiyaman@saiyaman-Lenovo-U310_0/38005/0/0), mkdir failed [1]
[saiyaman-Lenovo-U310:19025] [[38005,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[saiyaman-Lenovo-U310:19025] [[38005,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 402
[saiyaman-Lenovo-U310:19025] [[38005,0],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 638
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_session_dir failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
reading sources... [ 55%] features/building_blocks/drivers/scipy_optimize_driver                                         
   Normal return from subroutine COBYLA

   NFVALS =  124   F =-2.733333E+01    MAXCV = 0.000000E+00
   X = 6.666667E+00  -7.333332E+00
WARNING: autodoc: failed to import module 'openmdao.components.demux_comp'; the following exception was raised:          
No module named 'openmdao.components.demux_comp'
WARNING: autodoc: failed to import module 'openmdao.components.mux_comp'; the following exception was raised:
No module named 'openmdao.components.mux_comp'
WARNING: autodoc: failed to import module 'openmdao.test_suite.components.matmultcomp'; the following exception was raised:
No module named 'openmdao.test_suite.components.matmultcomp'
WARNING: autodoc: failed to import module 'openmdao.test_suite.tot_jac_builder'; the following exception was raised:
No module named 'openmdao.test_suite.tot_jac_builder'
WARNING: autodoc: failed to import module 'openmdao.vectors.petsc_transfer'; the following exception was raised:
No module named 'PETSc'
WARNING: autodoc: failed to import module 'openmdao.vectors.petsc_vector'; the following exception was raised:
No module named 'PETSc'
WARNING: autodoc: failed to import method 'MuxComp.add_var' from module 'openmdao.components.mux_comp'; the following exception was raised:
No module named 'openmdao.components.mux_comp'
WARNING: autodoc: failed to import method 'DemuxComp.add_var' from module 'openmdao.components.demux_comp'; the following exception was raised:
No module named 'openmdao.components.demux_comp'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/components/mux_demux_comps.rst:62: WARNING: No module named 'openmdao.components.tests.test_demux_comp'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/components/mux_demux_comps.rst:74: WARNING: No module named 'openmdao.components.tests.test_mux_comp'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/drivers/doe_driver.rst:73: WARNING: Running of embedded code openmdao.drivers.tests.test_doe_driver.TestParallelDOEFeature.test_full_factorial in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 681, in run_code
    with open('%d.out' % i) as f:
FileNotFoundError: [Errno 2] No such file or directory: '0.out'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/drivers/doe_driver.rst:102: WARNING: Running of embedded code openmdao.drivers.tests.test_doe_driver.TestParallelDOEFeature2.test_fan_in_grouped in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 681, in run_code
    with open('%d.out' % i) as f:
FileNotFoundError: [Errno 2] No such file or directory: '0.out'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/drivers/genetic_algorithm.rst:82: WARNING: type object 'TestFeatureSimpleGA' has no attribute 'test_constrained_with_penalty'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/drivers/genetic_algorithm.rst:93: WARNING: Running of embedded code openmdao.drivers.tests.test_genetic_algorithm_driver.MPIFeatureTests.test_option_parallel in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 681, in run_code
    with open('%d.out' % i) as f:
FileNotFoundError: [Errno 2] No such file or directory: '0.out'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/drivers/genetic_algorithm.rst:107: WARNING: Running of embedded code openmdao.drivers.tests.test_genetic_algorithm_driver.MPIFeatureTests4.test_option_procs_per_model in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 681, in run_code
    with open('%d.out' % i) as f:
FileNotFoundError: [Errno 2] No such file or directory: '0.out'
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/solvers/linear/linear_user_defined.rst:39: WARNING: Running of embedded code openmdao.solvers.linear.tests.test_user_defined.TestUserDefinedSolver.test_feature in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 736, in run_code
    exec(code_to_run, globals_dict)
  File "<string>", line 119, in <module>
  File "/usr/local/lib/python3.6/dist-packages/openmdao/solvers/linear/petsc_ksp.py", line 188, in __init__
    raise RuntimeError("PETSc is not available.")
RuntimeError: PETSc is not available.
/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/features/building_blocks/solvers/linear/petsc_krylov.rst:19: WARNING: Running of embedded code openmdao.solvers.linear.tests.test_petsc_ksp.TestPETScKrylovSolverFeature.test_specify_solver in docs failed due to: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openmdao/docs/_utils/docutil.py", line 736, in run_code
    exec(code_to_run, globals_dict)
  File "<string>", line 29, in <module>
  File "/usr/local/lib/python3.6/dist-packages/openmdao/solvers/linear/petsc_ksp.py", line 188, in __init__
    raise RuntimeError("PETSc is not available.")
RuntimeError: PETSc is not available.

Exception occurred:
  File "/usr/local/lib/python3.6/dist-packages/openmdao/solvers/linear/petsc_ksp.py", line 188, in __init__
    raise RuntimeError("PETSc is not available.")
RuntimeError: PETSc is not available.
The full traceback has been saved in /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/sphinx-err-oph9e12p.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:66: recipe for target 'buildall' failed
make: *** [buildall] Error 2
```
sphinx-err-oph9e12p.log below:
```
# Sphinx version: 1.7.9
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 58%] features/building_blocks/solvers/linear/linear_block_gs
#   
#   reading sources... [ 58%] features/building_blocks/solvers/linear/linear_block_jac
#   
#   reading sources... [ 58%] features/building_blocks/solvers/linear/linear_runonce
#   
#   reading sources... [ 59%] features/building_blocks/solvers/linear/linear_user_defined
#   
#   reading sources... [ 59%] features/building_blocks/solvers/linear/petsc_krylov
#   
# Loaded extensions:
#   alabaster (0.7.11) from /usr/local/lib/python3.6/dist-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/doctest.py
#   sphinx.ext.todo (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/coverage.py
#   sphinx.ext.mathjax (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/mathjax.py
#   sphinx.ext.viewcode (1.7.9) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/viewcode.py
#   numpydoc (0.8.0) from /usr/local/lib/python3.6/dist-packages/numpydoc/__init__.py
#   embed_code (1.7.9) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_code.py
#   embed_options (1.7.9) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_options.py
#   embed_compare (1.7.9) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_compare.py
#   embed_shell_cmd (1.7.9) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_shell_cmd.py
#   embed_bibtex (1.7.9) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_bibtex.py
#   tags (0.1) from /home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/tags.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/environment/__init__.py", line 662, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/io.py", line 302, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.6/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python3.6/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/local/lib/python3.6/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2988, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/saiyaman/gitrepos/cloned/OpenMDAO/openmdao/docs/_exts/embed_options.py", line 40, in run
    options = getattr(klass(), attribute_name)
  File "/usr/local/lib/python3.6/dist-packages/openmdao/solvers/linear/petsc_ksp.py", line 188, in __init__
    raise RuntimeError("PETSc is not available.")
RuntimeError: PETSc is not available.
```

**Comment by kmarsteller** [comment]
@capsulecorplab do you have, or can you get OpenMDAO 2.4 and report back as to whether you still have this issue? We are successfully able to build docs in an env without PETSc. Will investigate more if your problem persists.
